#!/bin/env python3
"""Expand ruff config's extend attribute and write it out.

By default, it read's current git repo's root pyproject.toml and writes out
(without comments or previous formatting) to .ruff.toml

This is useful to flatten ruff configs e.g. when "extend" points to a local config
which isn't available on CI/CD.
"""

import argparse
import logging
import os
import shutil
import subprocess
from collections import ChainMap
from collections.abc import Sequence
from pathlib import Path
from string import Template

import toml_rs  # I/O, fast and compatible with TOML v1.0 and v1.1
from rich.console import Console
from rich.logging import RichHandler
from rich.pretty import pretty_repr

CONSOLE = Console()
"""Common console used throughout this script."""

DEFAULT_IN = "pyproject.toml"
"""Filename at base of git repo to find ruff configs from."""

DEFAULT_OUT = ".ruff.toml"
"""Filename at base of git repo to write out expanded configs from."""

logging.basicConfig(
    level="NOTSET",
    format="%(message)s",
    datefmt="[%X]",
    handlers=[RichHandler(console=CONSOLE, rich_tracebacks=True)],
)
LOGGER = logging.getLogger("expand-ruff-extend")
LOGGER.setLevel(logging.WARNING)


def log_json(data: object, level: int = logging.DEBUG, name: str | None = None) -> None:
    """Log message for JSON data given, by default to debug."""
    msg = pretty_repr(data, max_width=CONSOLE.width, expand_all=True)
    LOGGER.log(level, f"{name} = {msg}" if name else msg)


def get_repo_root() -> Path:
    """Fetch path to git repository root based off current working directory."""
    if not (git := shutil.which("git")):
        msg = "No git executable found"
        raise OSError(msg)
    try:
        result = subprocess.run(
            [git, "rev-parse", "--show-toplevel"],
            capture_output=True,
            text=True,
            check=False,
        )
    except subprocess.CalledProcessError as error:
        msg = "Probably not run from a git repository"
        raise OSError(msg) from error
    return Path(result.stdout.strip())


def ruff_contents(toml_path: Path) -> dict:
    """Fetch ruff settings from given TOML file path."""
    results = {}
    if toml_path.is_file():
        LOGGER.info(f"Reading: {toml_path}")
        contents: dict = toml_rs.loads(toml_path.read_text())
        results: dict = (
            contents.get("tool", {}).get("ruff", {})
            if toml_path.name == "pyproject.toml"
            else contents
        )
    return results


def deep_merged(base: dict, updates: dict) -> dict:
    """Apply updates onto base dict, recursively merging sub-dicts."""
    return {
        key: (
            deep_merged(base_dict, updates_dict)
            if isinstance(base_dict := base.get(key), dict)
            and isinstance(updates_dict := updates.get(key), dict)
            else value
        )
        for key, value in dict(ChainMap(updates, base)).items()
    }


def expanded_contents(in_toml: Path) -> str:
    """Expand and dump config string that will be read from given path.

    If no "extend" property is found, then empty string is returned (no expansion
    took place).
    """
    heading = f"# Auto-generated from expanding out {in_toml.name}"
    config: dict = ruff_contents(in_toml)
    log_json(config, name="(base) config")
    if extend := config.pop("extend", None):
        extend_path = Path(Template(extend).substitute(os.environ))
        config: dict = deep_merged(ruff_contents(extend_path), config)
        log_json(config, name="(merged) config")
    else:
        LOGGER.warning("No extend property found")
    return "" if extend is None and config else f"{heading}\n{toml_rs.dumps(config)}"


def _cli(argv: Sequence[str] | None = None) -> None:
    module_docstrings = str(__doc__)  # Ensure at least 1 empty line in there!
    description, epilog = module_docstrings.split("\n\n", 1)
    parser = argparse.ArgumentParser(
        Path(__file__).name,
        description=description,
        epilog=epilog,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    v_help = "Verbosity (of LOGGER). WARNING by default, -v: INFO, -vv: DEBUG"
    parser.add_argument("-v", help=v_help, action="count", default=0)
    config_suffix = " config file name (at git repo root)"
    parser.add_argument("-i", help=f"Input {config_suffix}", default=DEFAULT_IN)
    parser.add_argument("-o", help=f"Output {config_suffix}", default=DEFAULT_OUT)

    args = parser.parse_args(argv)
    LOGGER.setLevel([logging.WARNING, logging.INFO, logging.DEBUG][args.v])
    repo_root = get_repo_root()
    if out_text := expanded_contents(repo_root / args.i):
        out_toml = repo_root / args.o
        out_toml.write_text(out_text)
        LOGGER.info(f"Written expanded to: {out_toml}")
    else:
        LOGGER.warning("No expanded ruff configs to write")


if __name__ == "__main__":
    _cli()
