[project]
name = "expand-ruff-extend"
version = "0.2.0"
description = "Expand ruff config's extend attribute and write it out"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "rich>=14.2.0",
    "toml-rs>=0.2.2",
]

[project.scripts]
expand-ruff-extend = "expand_ruff_extend._cli:main"

[tool.uv]
package = true